name: flights-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - pip:
      # Optional: additional packages that pip handles
      - xgboost
      - lightgbm
